# Node.js
# Build a general Node.js project with yarn.

trigger:
- master

variables:
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Test
        displayName: Test        
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            inputs: 
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              yarn install
              yarn test
            displayName: 'yarn install and test'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'